version: '3.8'

services:
  adwebstart-webapp:
    image: adwebstart-webapp:latest
    container_name: adwebstart-webapp
    restart: "no"
    ports:
      - "3000:3000"
    networks:
      - adwebstart

networks:
  adwebstart:
    driver: bridge

