version: '3.8'

services:
  adwebstart-react:
    image: adwebstart-react:latest
    container_name: adwebstart-react
    restart: "no"
    ports:
      - "3001:3000"
    networks:
      - adwebstart

networks:
  adwebstart:
    driver: bridge

