version: '3.8'

services:
  adwebstart-db:
    image: adwebstart-db:latest
    container_name: adwebstart-db
    restart: "no"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - adwebstart:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    networks:
      - adwebstart

  adwebstart:
    image: adwebstart:latest
    container_name: adwebstart
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://adwebstart-db:5432/adwebstart
      SPRING_DATASOURCE_USERNAME: adwebstart
      SPRING_DATASOURCE_PASSWORD: adwebstart
    depends_on: 
      - adwebstart-db
    ports:
      - "9000:9000"
    volumes:
      - adwebstart:/opt/adwebstart
      - adwebstart:/var/lib/postgresql/data
    networks:
      - adwebstart

  adwebstart-webapp:
    image: adwebstart-webapp:latest
    container_name: adwebstart-webapp
    depends_on:
      - adwebstart
    ports:
      - "3000:3000"
    networks:
      - adwebstart


volumes:
  adwebstart:
    driver: local

networks:
  adwebstart:
    driver: bridge

