version: '3.8'

services:
  adwebstart:
    image: adwebstart:latest
    container_name: adwebstart
    volumes:
      - adwebstart:/opt/adwebstart
      - adwebstart:/var/lib/postgresql/data
    ports:
      - "9000:9000"
    networks:
      - adwebstart

volumes:
  adwebstart:
    driver: local

networks:
  adwebstart:
    driver: bridge

